# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\023grpc.server.Service',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nenum.proto*6\n\rReadingStatus\x12\x0b\n\x07Invalid\x10\x00\x12\x0b\n\x07Success\x10\x01\x12\x0b\n\x07\x46\x61ilure\x10\x02\x42\x16\xaa\x02\x13grpc.server.Serviceb\x06proto3'
)

_READINGSTATUS = _descriptor.EnumDescriptor(
  name='ReadingStatus',
  full_name='ReadingStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Success', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failure', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=14,
  serialized_end=68,
)
_sym_db.RegisterEnumDescriptor(_READINGSTATUS)

ReadingStatus = enum_type_wrapper.EnumTypeWrapper(_READINGSTATUS)
Invalid = 0
Success = 1
Failure = 2


DESCRIPTOR.enum_types_by_name['ReadingStatus'] = _READINGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
